all:
  children:
    demo:
      hosts:
        syncdoc-demo-02:
          ansible_host: 192.0.2.11
          app_env: stage
          syncdoc_state: drifted-again
        syncdoc-demo-03:
          ansible_host: 192.0.2.12
          app_env: stage
          syncdoc_state: drifted-again
