all:
  children:
    demo:
      hosts:
        syncdoc-demo-01:
          ansible_host: 192.0.2.10
          app_env: dev
          syncdoc_state: baseline
        syncdoc-demo-02:
          ansible_host: 192.0.2.11
          app_env: dev
          syncdoc_state: baseline
